- name: Atualizar sistema
  apt:
    update_cache: yes
    upgrade: dist

- name: Instalar chrony e definir NTP
  apt:
    name: chrony
    state: present

- name: Configurar chrony para usar pool.ntp.br
  lineinfile:
    path: /etc/chrony/chrony.conf
    regexp: '^pool'
    line: 'pool pool.ntp.br iburst'
  notify: restart chrony

- name: Ajustar fuso horário
  timezone:
    name: America/Recife

- name: Criar grupo ifpb
  group:
    name: ifpb

- name: Criar usuários jantony e jonatas
  user:
    name: "{{ item }}"
    groups: ifpb
    shell: /bin/bash
  loop:
    - jantony
    - jonatas

- name: Criar .ssh e autorizar chave
  authorized_key:
    user: "{{ item }}"
    state: present
    key: "{{ lookup('file', 'roles/common/files/{{ item }}.pub') }}"
  loop:
    - jantony
    - jonatas

- name: Instalar SSH
  apt:
    name: openssh-server
    state: present

- name: Desabilitar login root via SSH
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin no'

- name: Permitir apenas autenticação por chave pública
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: 'PasswordAuthentication no'

- name: Restringir acesso SSH a grupos
  lineinfile:
    path: /etc/ssh/sshd_config
    line: 'AllowGroups vagrant ifpb'

- name: Definir banner SSH
  copy:
    src: ssh-banner
    dest: /etc/issue.net

- name: Ativar banner no SSH
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^Banner'
    line: 'Banner /etc/issue.net'

- name: Instalar cliente NFS
  apt:
    name: nfs-common
    state: present

- name: Permitir sudo para grupo ifpb
  lineinfile:
    path: /etc/sudoers
    line: '%ifpb ALL=(ALL) NOPASSWD:ALL'
    validate: '/usr/sbin/visudo -cf %s'

handlers:
  - name: restart chrony
    service:
      name: chrony
      state: restarted

  - name: restart ssh
    service:
      name: ssh
      state: restarted

