---
# ansible/roles/nfs_server/tasks/main.yml

- name: Instalar o servidor NFS (nfs-kernel-server)
  ansible.builtin.apt:
    name: nfs-kernel-server
    state: present

- name: Criar o diretório de compartilhamento NFS /dados/nfs
  ansible.builtin.file:
    path: /dados/nfs
    state: directory
    owner: root
    group: root
    mode: '0777' # Permissão temporária, ajustaremos com o usuário nfs-ifpb

- name: Criar usuário nfs-ifpb com shell nologin
  ansible.builtin.user:
    name: nfs-ifpb
    state: present
    shell: /usr/sbin/nologin
    system: yes # Usuário do sistema

- name: Alterar propriedade do diretório /dados/nfs para nfs-ifpb
  ansible.builtin.file:
    path: /dados/nfs
    owner: nfs-ifpb
    group: nfs-ifpb
    mode: '0770' # Ajustar permissões para permitir escrita apenas ao nfs-ifpb

- name: Configurar exportações NFS
  ansible.builtin.template:
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: '0644'
  notify: Exportar compartilhamentos NFS

- name: Habilitar e iniciar o serviço NFS
  ansible.builtin.service:
    name: nfs-kernel-server
    state: started
    enabled: yes
