---
# ansible/arq.yml
# Playbook para configurar o servidor de arquivos 'arq'

- name: Configurar servidor de arquivos (arq)
  hosts: arq
  become: yes
  vars_files:
    - ../vars/main.yml

  roles:
    - dhcp_server
    - nfs_server
    # LVM será tratado em tasks específicas pois não é uma role genérica simples
  tasks:
    # --- Configuração do LVM ---
    - name: Garantir que os pacotes lvm2 estejam instalados
      ansible.builtin.apt:
        name: lvm2
        state: present

    - name: Criar Physical Volumes (PVs) nos 3 discos adicionais
      community.general.pvcreate:
        vg: dados # Necessário especificar para o pvcreate
        # Para descobrir os nomes dos dispositivos: Rode `lsblk` ou `fdisk -l` na VM
        # Os nomes dos dispositivos podem variar (ex: /dev/sdb, /dev/sdc, /dev/sdd)
        # É CRÍTICO identificar os nomes corretos dos discos VA_
        # Este exemplo assume sdb, sdc, sdd. Ajuste conforme necessário.
        disks:
          - /dev/sdb
          - /dev/sdc
          - /dev/sdd

    - name: Criar Volume Group (VG) 'dados'
      community.general.vgcreate:
        vg: dados
        pvs: /dev/sdb,/dev/sdc,/dev/sdd # Liste todos os PVs criados

    - name: Criar Logical Volume (LV) 'ifpb' de 15GB no VG 'dados'
      community.general.lvcreate:
        vg: dados
        lv: ifpb
        size: 15G

    - name: Formatar o Logical Volume 'ifpb' com ext4
      ansible.builtin.filesystem:
        fstype: ext4
        dev: /dev/mapper/dados-ifpb # Caminho padrão para LV

    - name: Criar ponto de montagem /dados
      ansible.builtin.file:
        path: /dados
        state: directory
        mode: '0755'

    - name: Configurar montagem automática do LV 'ifpb' em /dados
      ansible.posix.mount:
        path: /dados
        src: /dev/mapper/dados-ifpb
        fstype: ext4
        state: mounted
        opts: defaults
